# ---------------------------------------------------------
# NB! Ikke bruk de norske bokstavene i kommentarer her !!!
# ---------------------------------------------------------

# Her sier vi at applikasjonen har et navn, og at ressurser
# er relativt under denne, f.eks.
#     localhost:8080/f15app/personliste-ssr
server.servlet.context-path=/f15app

# Her gir vi bekjed til Jackson at JSON som blir generert skal vare
# fint strukturert med linjeskift og innrykk
spring.jackson.serialization.indent_output=true

# Her gir vi bekjed om hvor mye loggedetaljer vi onsker
# Nivaaene er TRACE, DEBUG, INFO, WARN, ERROR
logging.level.root=INFO
logging.level.org.springframework.web=INFO